### ISSUE TITLE
Bar 6

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI-WotLK/ElvUI_ExtraActionBars#2]
What happened to bar 6? Haha

![wowscrnshot_090416_190305](https://cloud.githubusercontent.com/assets/7307335/18234679/5dfb7108-72d2-11e6-9d08-83a2b3f39ad8.jpg)
![wowscrnshot_090416_190319](https://cloud.githubusercontent.com/assets/7307335/18234680/5e074b4a-72d2-11e6-9354-9d2c691abb98.jpg)

**Comment by Bunny67** [comment]
6 bar is not finished

**Comment by Bunny67** [comment]
fixed
